[workspace]
resolver = "3"
members = ["crates/core-common", "crates/core-math", "crates/core-graph"]
[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
[workspace.dependencies]
core-common = { path = "crates/core-common" }
core-math = { path = "crates/core-math" }
core-graph = { path = "crates/core-graph" }
thiserror = "2"
