[package]
name = "core-rs-android"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
core-search.workspace = true
core-math.workspace = true
core-graph.workspace = true
core-binary.workspace = true
jni.workspace = true
serde_json.workspace = true
